{% set version = "2.3.1" %}

package:
  name: sedflux
  version: {{ version }}

source:
  url: https://github.com/mcflugen/sedflux/archive/v{{ version }}.tar.gz
  sha256: a0b053630ed4bf309877d68dfc62d343695a729708efb49a582ff9f8e91b677b

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake
    - pkg-config
    - gnuconfig  # [unix]
    - {{ compiler('cxx') }}
  host:
    - glib
  run:
    - glib

test:
  commands:
    - sedflux -h

about:
  home: https://github.com/mcflugen/sedflux
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A stratigraphic basin-filling model
  description: |
    Sedflux-2.0 is the newest version of the Sedflux basin-filling
    model. Sedflux-2.0 provides a framework within which individual
    process-response models of disparate time and space resolutions
    communicate with one another to deliver multi grain sized
    sediment load across a continental margin.
  doc_url: http://sedflux.readthedocs.io/
  dev_url: http://github.com/mcflugen/sedflux

extra:
  recipe-maintainers:
    - mcflugen
