{% set version = "2.2.6" %}

package:
  name: sedflux
  version: {{ version }}

source:
  url: https://github.com/mcflugen/sedflux/archive/v{{ version }}.tar.gz
  sha256: 3f6e9cb87d8fb08f3737daaf7c9e3847efcb640e5ed1ede0b10c305d07610237

build:
  number: 1000
  skip: True  # [win]

requirements:
  build:
    - cmake
    - pkg-config
    - {{ compiler('cxx') }}
  host:
    - glib
  run:
    - glib

test:
  commands:
    - sedflux -h

about:
  home: https://github.com/mcflugen/sedflux
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A stratigraphic basin-filling model
  description: |
    Sedflux-2.0 is the newest version of the Sedflux basin-filling
    model. Sedflux-2.0 provides a framework within which individual
    process-response models of disparate time and space resolutions
    communicate with one another to deliver multi grain sized
    sediment load across a continental margin.
  doc_url: http://sedflux.readthedocs.io/
  dev_url: http://github.com/mcflugen/sedflux

extra:
  recipe-maintainers:
    - mcflugen
