appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: H44ZiWLZHxlYjWRcsB8l5LYXiddi2JNwkthNIahRuwhQLOdQJTuqAD5CeLNz9rmypSrsQMNDo8B9ucvBQ3JCnn6x+L7USqgNFF2YnUGTyiCkrPdyeQo5S+ts0PF6g6oqanE4nbLkjAJca/w6xQu6WjzAgtF5oG8+s5nQntZGnzf5StV5jWjx3bMR2LEX9LrJi3qVZulT6/o8aLfec+Wk6sM2eHPlwZ6QtNUlDUOl1EbCwlHcmrGXP/iXCe2SZHn40UbNKN3uhug3BDv+AtVAoPVaSTf4Il34DYly4e4kkob4yizj4ic57XIUyNfpaE9i38wCwUdpozyMBTXZotZcdECgCm82+YmU3Xlw4yMeCFoYxo8TwWj9JjVjIi2+g9q0OwPhi3ctCuhSlVLy5eYk9zn+UToyaQ9b/cIxh84OO447bqgm7UJn1G9Ono8VIYSbYbx7vVNOWLgidMkFnkeq6ecHu7PTk7+VuMpENrHW8ERD3CbdVILTIeybVHxVOKoYGb5b3Jxdx/yOtK50iTkIgcC/AlHF/eby8isidJpntFfuEDqroNRWKgwMp+vPHzCGuMORzCcANQZlB7ROybnyJkuE4KeJW4JHCli76thJDl+pzzU46XIbFRDM7hOUa/qRGecY4e8zen8wJ2nK+ff5vnMTZOkg3VpF7M/Z75JHzCE=}
conda_forge_output_validation: true
